import { BaseEventManager } from "../../events/BaseEventManager";
import type { InGameManager } from "../InGameManager";
import { InGameBlockExplode } from "./BlockExplode";
import { InGameButtonPush } from "./ButtonPush";
import { InGameDataDrivenEntityTrigger } from "./DataDrivenEntityTrigger";
import { InGameEffectAdd } from "./EffectAdd";
import { InGameEntityDie } from "./EntityDie";
import { InGameEntityHealthChanged } from "./EntityHealthChanged";
import { InGameEntityHitBlock } from "./EntityHitBlock";
import { InGameEntityHitEntity } from "./EntityHitEntity";
import { InGameEntityHurt } from "./EntityHurt";
import { InGameEntityLoad } from "./EntityLoad";
import { InGameEntityRemove } from "./EntityRemove";
import { InGameEntitySpawn } from "./EntitySpawn";
import { InGameExplosion } from "./Explosion";
import { InGameGameRuleChange } from "./GameRuleChange";
import { InGameItemCompleteUse } from "./ItemCompleteUse";
import { InGameItemReleaseUse } from "./ItemReleaseUse";
import { InGameItemStartUse } from "./ItemStartUse";
import { InGameItemStartUseOn } from "./ItemStartUseOn";
import { InGameItemStopUse } from "./ItemStopUse";
import { InGameItemStopUseOn } from "./ItemStopUseOn";
import { InGameItemUse } from "./ItemUse";
import { InGameLeverAction } from "./LeverAction";
import { InGamePistonActivate } from "./PistonActivate";
import { InGamePlayerBreakBlock } from "./PlayerBreakBlock";
import { InGamePlayerButtonInput } from "./PlayerButtonInput";
import { InGamePlayerDimensionChange } from "./PlayerDimensionChange";
import { InGamePlayerEmote } from "./PlayerEmote";
import { InGamePlayerGameModeChange } from "./PlayerGameModeChange";
import { InGamePlayerHotbarSelectedSlotChange } from "./PlayerHotbarSelectedSlotChange";
import { InGamePlayerInputModeChange } from "./PlayerInputModeChange";
import { InGamePlayerInputPermissionCategoryChange } from "./PlayerInputPermissionCategoryChange";
import { InGamePlayerInteractWithBlock } from "./PlayerInteractWithBlock";
import { InGamePlayerInteractWithEntity } from "./PlayerInteractWithEntity";
import { InGamePlayerInventoryItemChange } from "./PlayerInventoryItemChange";
import { InGamePlayerJoin } from "./PlayerJoin";
import { InGamePlayerLeave } from "./PlayerLeave";
import { InGamePlayerPlaceBlock } from "./PlayerPlaceBlock";
import { InGamePlayerSpawn } from "./PlayerSpawn";
import { InGamePressurePlatePop } from "./PressurePlatePop";
import { InGamePressurePlatePush } from "./PressurePlatePush";
import { InGameProjectileHitBlock } from "./ProjectileHitBlock";
import { InGameProjectileHitEntity } from "./projectileHitEntity";
import { InGameTargetBlockHit } from "./TargetBlockHit";
import { InGameWeatherChange } from "./WeatherChange";

export class InGameEventManager extends BaseEventManager {
    private readonly blockExplode: InGameBlockExplode;
    private readonly buttonPush: InGameButtonPush;
    private readonly dataDrivenEntityTrigger: InGameDataDrivenEntityTrigger;
    private readonly effectAdd: InGameEffectAdd;
    private readonly entityDie: InGameEntityDie;
    private readonly entityHealthChanged: InGameEntityHealthChanged;
    private readonly entityHitBlock: InGameEntityHitBlock;
    private readonly entityHitEntity: InGameEntityHitEntity;
    private readonly entityHurt: InGameEntityHurt;
    private readonly entityLoad: InGameEntityLoad;
    private readonly entityRemove: InGameEntityRemove;
    private readonly entitySpawn: InGameEntitySpawn;
    private readonly explosion: InGameExplosion;
    private readonly gameRuleChange: InGameGameRuleChange;
    private readonly itemCompleteUse: InGameItemCompleteUse;
    private readonly itemReleaseUse: InGameItemReleaseUse;
    private readonly itemStartUse: InGameItemStartUse;
    private readonly itemStartUseOn: InGameItemStartUseOn;
    private readonly itemStopUse: InGameItemStopUse;
    private readonly itemStopUseOn: InGameItemStopUseOn;
    private readonly itemUse: InGameItemUse;
    private readonly leverAction: InGameLeverAction;
    private readonly pistonActivate: InGamePistonActivate;
    private readonly playerBreakBlock: InGamePlayerBreakBlock;
    private readonly playerButtonInput: InGamePlayerButtonInput;
    private readonly playerDimensionChange: InGamePlayerDimensionChange;
    private readonly playerEmote: InGamePlayerEmote;
    private readonly playerGameModeChange: InGamePlayerGameModeChange;
    private readonly playerHotbarSelectedSlotChange: InGamePlayerHotbarSelectedSlotChange;
    private readonly playerInputModeChange: InGamePlayerInputModeChange;
    private readonly playerInputPermissionCategoryChange: InGamePlayerInputPermissionCategoryChange;
    private readonly playerInteractWithBlock: InGamePlayerInteractWithBlock;
    private readonly playerInteractWithEntity: InGamePlayerInteractWithEntity;
    private readonly playerInventoryItemChange: InGamePlayerInventoryItemChange;
    private readonly playerJoin: InGamePlayerJoin;
    private readonly playerLeave: InGamePlayerLeave;
    private readonly playerPlaceBlock: InGamePlayerPlaceBlock;
    private readonly playerSpawn: InGamePlayerSpawn;
    private readonly pressurePlatePop: InGamePressurePlatePop;
    private readonly pressurePlatePush: InGamePressurePlatePush;
    private readonly projectileHitBlock: InGameProjectileHitBlock;
    private readonly projectileHitEntity: InGameProjectileHitEntity;
    private readonly targetBlockHit: InGameTargetBlockHit;
    private readonly weatherChange: InGameWeatherChange;

    private constructor(private readonly inGameManager: InGameManager) {
        super();
        this.blockExplode = InGameBlockExplode.create(this);
        this.buttonPush = InGameButtonPush.create(this);
        this.dataDrivenEntityTrigger = InGameDataDrivenEntityTrigger.create(this);
        this.effectAdd = InGameEffectAdd.create(this);
        this.entityDie = InGameEntityDie.create(this);
        this.entityHealthChanged = InGameEntityHealthChanged.create(this);
        this.entityHitBlock = InGameEntityHitBlock.create(this);
        this.entityHitEntity = InGameEntityHitEntity.create(this);
        this.entityHurt = InGameEntityHurt.create(this);
        this.entityLoad = InGameEntityLoad.create(this);
        this.entityRemove = InGameEntityRemove.create(this);
        this.entitySpawn = InGameEntitySpawn.create(this);
        this.explosion = InGameExplosion.create(this);
        this.gameRuleChange = InGameGameRuleChange.create(this);
        this.itemCompleteUse = InGameItemCompleteUse.create(this);
        this.itemReleaseUse = InGameItemReleaseUse.create(this);
        this.itemStartUse = InGameItemStartUse.create(this);
        this.itemStartUseOn = InGameItemStartUseOn.create(this);
        this.itemStopUse = InGameItemStopUse.create(this);
        this.itemStopUseOn = InGameItemStopUseOn.create(this);
        this.itemUse = InGameItemUse.create(this);
        this.leverAction = InGameLeverAction.create(this);
        this.pistonActivate = InGamePistonActivate.create(this);
        this.playerBreakBlock = InGamePlayerBreakBlock.create(this);
        this.playerButtonInput = InGamePlayerButtonInput.create(this);
        this.playerDimensionChange = InGamePlayerDimensionChange.create(this);
        this.playerEmote = InGamePlayerEmote.create(this);
        this.playerGameModeChange = InGamePlayerGameModeChange.create(this);
        this.playerHotbarSelectedSlotChange = InGamePlayerHotbarSelectedSlotChange.create(this);
        this.playerInputModeChange = InGamePlayerInputModeChange.create(this);
        this.playerInputPermissionCategoryChange =
            InGamePlayerInputPermissionCategoryChange.create(this);
        this.playerInteractWithBlock = InGamePlayerInteractWithBlock.create(this);
        this.playerInteractWithEntity = InGamePlayerInteractWithEntity.create(this);
        this.playerInventoryItemChange = InGamePlayerInventoryItemChange.create(this);
        this.playerJoin = InGamePlayerJoin.create(this);
        this.playerLeave = InGamePlayerLeave.create(this);
        this.playerPlaceBlock = InGamePlayerPlaceBlock.create(this);
        this.playerSpawn = InGamePlayerSpawn.create(this);
        this.pressurePlatePop = InGamePressurePlatePop.create(this);
        this.pressurePlatePush = InGamePressurePlatePush.create(this);
        this.projectileHitBlock = InGameProjectileHitBlock.create(this);
        this.projectileHitEntity = InGameProjectileHitEntity.create(this);
        this.targetBlockHit = InGameTargetBlockHit.create(this);
        this.weatherChange = InGameWeatherChange.create(this);
    }

    public static create(inGameManager: InGameManager): InGameEventManager {
        return new InGameEventManager(inGameManager);
    }

    public override subscribeAll(): void {
        this.blockExplode.subscribe();
        this.buttonPush.subscribe();
        this.dataDrivenEntityTrigger.subscribe();
        this.effectAdd.subscribe();
        this.entityDie.subscribe();
        this.entityHealthChanged.subscribe();
        this.entityHitBlock.subscribe();
        this.entityHitEntity.subscribe();
        this.entityHurt.subscribe();
        this.entityLoad.subscribe();
        this.entityRemove.subscribe();
        this.entitySpawn.subscribe();
        this.explosion.subscribe();
        this.gameRuleChange.subscribe();
        this.itemCompleteUse.subscribe();
        this.itemReleaseUse.subscribe();
        this.itemStartUse.subscribe();
        this.itemStartUseOn.subscribe();
        this.itemStopUse.subscribe();
        this.itemStopUseOn.subscribe();
        this.itemUse.subscribe();
        this.leverAction.subscribe();
        this.pistonActivate.subscribe();
        this.playerBreakBlock.subscribe();
        this.playerButtonInput.subscribe();
        this.playerDimensionChange.subscribe();
        this.playerEmote.subscribe();
        this.playerGameModeChange.subscribe();
        this.playerHotbarSelectedSlotChange.subscribe();
        this.playerInputModeChange.subscribe();
        this.playerInputPermissionCategoryChange.subscribe();
        this.playerInteractWithBlock.subscribe();
        this.playerInteractWithEntity.subscribe();
        this.playerInventoryItemChange.subscribe();
        this.playerJoin.subscribe();
        this.playerLeave.subscribe();
        this.playerPlaceBlock.subscribe();
        this.playerSpawn.subscribe();
        this.pressurePlatePop.subscribe();
        this.pressurePlatePush.subscribe();
        this.projectileHitBlock.subscribe();
        this.projectileHitEntity.subscribe();
        this.targetBlockHit.subscribe();
        this.weatherChange.subscribe();
    }

    public override unsubscribeAll(): void {
        this.blockExplode.unsubscribe();
        this.buttonPush.unsubscribe();
        this.dataDrivenEntityTrigger.unsubscribe();
        this.effectAdd.unsubscribe();
        this.entityDie.unsubscribe();
        this.entityHealthChanged.unsubscribe();
        this.entityHitBlock.unsubscribe();
        this.entityHitEntity.unsubscribe();
        this.entityHurt.unsubscribe();
        this.entityLoad.unsubscribe();
        this.entityRemove.unsubscribe();
        this.entitySpawn.unsubscribe();
        this.explosion.unsubscribe();
        this.gameRuleChange.unsubscribe();
        this.itemCompleteUse.unsubscribe();
        this.itemReleaseUse.unsubscribe();
        this.itemStartUse.unsubscribe();
        this.itemStartUseOn.unsubscribe();
        this.itemStopUse.unsubscribe();
        this.itemStopUseOn.unsubscribe();
        this.itemUse.unsubscribe();
        this.leverAction.unsubscribe();
        this.pistonActivate.unsubscribe();
        this.playerBreakBlock.unsubscribe();
        this.playerButtonInput.unsubscribe();
        this.playerDimensionChange.unsubscribe();
        this.playerEmote.unsubscribe();
        this.playerGameModeChange.unsubscribe();
        this.playerHotbarSelectedSlotChange.unsubscribe();
        this.playerInputModeChange.unsubscribe();
        this.playerInputPermissionCategoryChange.unsubscribe();
        this.playerInteractWithBlock.unsubscribe();
        this.playerInteractWithEntity.unsubscribe();
        this.playerInventoryItemChange.unsubscribe();
        this.playerJoin.unsubscribe();
        this.playerLeave.unsubscribe();
        this.playerPlaceBlock.unsubscribe();
        this.playerSpawn.unsubscribe();
        this.pressurePlatePop.unsubscribe();
        this.pressurePlatePush.unsubscribe();
        this.projectileHitBlock.unsubscribe();
        this.projectileHitEntity.unsubscribe();
        this.targetBlockHit.unsubscribe();
        this.weatherChange.unsubscribe();
    }

    public getInGameManager(): InGameManager {
        return this.inGameManager;
    }
}
